version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - idade-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - idade-network
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    secrets:
      - mysql_password

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    volumes:
      - db-data-idade:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - idade-network
    secrets:
      - mysql_root_password
      - mysql_password


volumes:
  db-data-idade:

networks:
  idade-network:

secrets:
  mysql_password:
    file: ./mysql_password
  mysql_root_password:
    file: ./mysql_root_password
